# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='123@qq.com', max_length=254),
            preserve_default=False,
        ),
    ]
