# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171204_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Post')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
    ]
