# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20171205_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='p',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app01.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='u',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
            preserve_default=False,
        ),
    ]
